### ISSUE TITLE
ProgrammingError: column c.paxs does not exist LINE 9:                     c.paxs as paxs,

### ISSUE THREAD

**Issue by jacksolutions** [openjaf/openerp_travel#1]
when installing this addon i am getting such error 

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/odoo/odoo/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/addons/travel_core/report/sale_report.py", line 101, in init
    )""" % (self._table, self._select(), self._from(), self._group_by()))
  File "/opt/odoo/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column c.paxs does not exist
LINE 9:                     c.paxs as paxs,

**Comment by jacksolutions** [comment]
any update on this one?

**Comment by yuriqp** [comment]
Error fixed

**Comment by jacksolutions** [comment]
thank you very much... is there any documentation on this module? what is the use of it and it usefullness? help will be appriciated.

Thanks

**Comment by sanchojaf** [comment]
Hi @jacksolutions 

We are working in the documentation.

This module is the core for our SaaS for Travel Agencies, you can visit here

https://www.comelytravel.com

Have free trial for one month.

We will send you a notice with some updated documentation.

Best,
OpenJAF Team.

**Comment by jacksolutions** [comment]
just registered got this error and this url

https://comelytravel.com/saas_server/new_database?access_token=9Q3rUYu8suUATRPFmKjL6ohR4pzkcj&token_type=Bearer&state={%22db_template%22:+%22standard%22,+%22u%22:+%22http://jacksolutions.comelytravel.com%22,+%22d%22:+%22jacksolutions_comelytravel_com%22}&expires_in=3600&scope=userinfo+force_login+trial+skiptheuse

 Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jacksolutions** [comment]
now end up with this after login 

http://awesomescreenshot.com/0564yqvadb

no modules loaded or found which are listed in repo

**Comment by sanchojaf** [comment]
Thanks for the feedback, we are reviewing now..

**Comment by jacksolutions** [comment]
any update on it?

**Comment by sanchojaf** [comment]
Hi,

Yes we did and updated, and hopefully the issue should be solved.

Thanks for your feedback, we will looking forward to hear from you any
other consideration.

Best,
OpenJAF Team.

2015-06-12 8:08 GMT-04:00 jacksolutions notifications@github.com:

**Comment by sanchojaf** [comment]
Hi

Was necessary restart your credential for try to fix the issue.

Please review an email that we sent to jaykishan.vansadawala@gmail.com
with the new credentials.

Please let me know any problem.

Best,
OpenJAF Team

2015-06-12 8:08 GMT-04:00 jacksolutions notifications@github.com:
